apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test-nov6-newapp 
  janus-idp.io/tekton: test-nov6-newapp
  backstage.io/kubernetes-id: test-nov6-newapp
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: test-nov6-newapp
resources: 
- application-dev.yaml